server:
  port: 9093

spring:
  application:
    name: bookstore-hystrix-dashboard

  #Config Server
  cloud:
    config:
      uri: http://localhost:8888
      name: bookstore-config-server

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/