server:
  port: 8083
spring:
  application:
    name: bookstore-order
  cloud:
    config:
      uri: http://localhost:8888
      name: bookstore-config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/