server:
  port: 9090

spring:
  application:
    name: bookstore-zuul-server

  #Config Server
  cloud:
    config:
      uri: http://localhost:8888
      name: bookstore-config-server

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

#Zuul Routing
zuul:
  routes:
    order: #routing id
      path: /order/** #zuul context root
      serviceId: bookstore-order #spring application name

    member:
      path: /member/**
      serviceId: bookstore-member

    goods:
      path: /goods/**
      serviceId: bookstore-goods